### ISSUE TITLE
Failed to learn in several tasks

### ISSUE THREAD

**Issue by Daffan** [RobertTLange/gymnax-blines#5]
Hi, I am trying this baseline, and found that the algorithm dose not learn in some tasks. For example, in MountainCarContinuous, the agent simply learns to not act (corresponds to reward close to 0), which is also reflected in the training curves you have showed. Do you think there might be a bug in the implementation? Thanks!

**Comment by RobertTLange** [comment]
Hi there,
Have you checked that your RL algorithm does learn on the original gym env? ContinuousMountainCar is a sparse environment on which many AC algorithms tend to fail due to bad exploration. All tests covering reset/step transitions succeed and I am fairly certain that there is no bug. What other environments trouble you?
Cheers,
Rob

**Comment by Daffan** [comment]
The discrete version of MountainCar also does not learn, and also the PointRobot-misc. PointRobot-misc by default has sparse reward, but I also tried the dense reward setting, but it still did not learn.

BTW, there are two small bugs that do not influence the training:
(1) utils/ppo.py line 112: self.env_params.replace() is not an in-place operation, which does not actually set the env_params;
(2) utils/ppo.py line 374: gae.mean() is always zero, since gae has already been normalized.

**Comment by RobertTLange** [comment]
Thanks for the pointers. Feel free to open a PR and contribute. Otherwise I will fix them at some point in the future.

For MountainCar the same argument as for the continuous version holds. I have previously trained agents with ES that are capable of solving the tasks.

Are you training a recurrent agent on the point robot task? It is a meta-learning task which requires exploration and subsequent exploitation. Simple FFW policies can’t really solve the task since they can’t adapt to changing goal locations between episodes.

**Comment by Daffan** [comment]
Okay, I finally found the bug. In utils/ppo.py line 346, it writes `log_prob = pi.log_prob(action[:, -1])` which works fine for discrete domains, but in the continuous domain, the shape of the action is actually (batch_size, action_dim, 1). So it will only take the value in the last dimension only, and broadcast to action_dim in following operations.

I was trying a customized simple 2D navigation domain with dense reward, but it simply just didn't work. It really bothered me, I knew something must be wrong.

Anyway, I will make a PR and contribute. Really thanks for the help!!

**Comment by RobertTLange** [comment]
Heyo, that’s a good point and I am looking forward to the PR. But this should not matter for continuous domains with 1d action space, right? Hence, for the considered environments in gymnax it is not introducing a bug.

**Comment by Daffan** [comment]
Yes, it only affect 1d action space. It should also be a problem for PointRobot-misc. I just trained PointRobot-misc without RNN, it at least can get positive rewards now (converges at around +3).

I created a PR. Thanks!

**Comment by RobertTLange** [comment]
Nice, thank you! It is merged.
